# Generated by Django 2.2.1 on 2019-07-19 01:08

from django.db import migrations, models
import stdimage.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(upload_to='apresentacao', verbose_name='Imagem')),
                ('missao', tinymce.models.HTMLField(verbose_name='Missao')),
                ('valores', tinymce.models.HTMLField(verbose_name='Valores')),
                ('visao', tinymce.models.HTMLField(verbose_name='Visao')),
            ],
            options={
                'verbose_name': 'Apresentacao',
                'verbose_name_plural': 'Apresentacoes',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(upload_to='depoimento', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Enfeite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('numero', models.CharField(max_length=100, verbose_name='Numero')),
                ('icon', models.CharField(max_length=100, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Enfeite',
                'verbose_name_plural': 'Enfeites',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(upload_to='galeroa', verbose_name='Imagem')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('imagem', stdimage.models.StdImageField(upload_to='parceiro', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição')),
                ('icon', stdimage.models.StdImageField(upload_to='servico', verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('imagem', stdimage.models.StdImageField(upload_to='time', verbose_name='Imagem')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('google', models.CharField(max_length=100, verbose_name='Google+')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('imagem', stdimage.models.StdImageField(upload_to='video', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
